
const EVENT_TYPES = {
    CELL_BURN_START: 'CELL_BURN_START',
    CELLS_BURN_START: 'CELLS_BURN_START',
    CELL_BURN_END: 'CELL_BURN_END',
    CELLS_BURN_END: 'CELLS_BURN_END',
}

export {EVENT_TYPES}