
const EVENT_TYPES = {
    CELL_BURN_START: 'CELL_BURN_START',
    CELLS_BURN_START: 'CELLS_BURN_START',
    CELL_BURN_END: 'CELL_BURN_END',
    CELLS_BURN_END: 'CELLS_BURN_END',
    POINTS_INCREMENTED: 'POINTS_INCREMENTED',
    FIELD_FILL_END: 'FIELD_FILL_END',
    FIELD_IS_UNPLAYABLE: 'FIELD_IS_UNPLAYABLE',
    UNPLAYABLE_FIELD_WAS_MIXED: 'UNPLAYABLE_FIELD_WAS_MIXED',
    CHECK_GAME_END: 'CHECK_GAME_END',
    BONUS_CHANGED: 'BONUS_CHANGED',
}

export {EVENT_TYPES}